### ISSUE TITLE
Script to generate data for 2D navier stokes

### ISSUE THREAD

**Issue by sjtuytc** [mkirchmeyer/DINo#1]
Thanks for your great work! I saw you provided some functions for data generation in 2D navier stokes, but you did not provide the running script for data generation. Also, I think the parameters for data generation are essential to produce your awesome work. It will be very beneficial that if you can release the code for data generation and I'm sure your work will have a greater impact.

**Comment by mkirchmeyer** [comment]
Hi, thank you for your message and interest ! If you launch the training script, the data will be automatically generated and stored in the path you have specified (c.f. https://github.com/mkirchmeyer/DINo/blob/main/utils.py#L86). All the parameters for data generation are specified here https://github.com/mkirchmeyer/DINo/blob/main/utils.py#L58
Please let us know if this does not work on your side.
Thanks

**Comment by sjtuytc** [comment]
Thanks for your quick response. I didn't find the checkpoint of the DW in the given drive. Can you take a look？

**Comment by sjtuytc** [comment]
I mean SW shallow water's checkpoint is missing.![image](https://github.com/mkirchmeyer/DINo/assets/31123348/57729028-457e-4148-b1ee-bef72c1e2846)

**Comment by sjtuytc** [comment]
![image](https://github.com/mkirchmeyer/DINo/assets/31123348/36813d65-9470-4351-8b20-fd96d0b49dff)

**Comment by mkirchmeyer** [comment]
yes we did not upload the corresponding checkpoints unfortunately. However, you can perform a full training using our scripts and you should find a similar results after training !

**Comment by sjtuytc** [comment]
Sure I'll do that. Thanks.
