### ISSUE TITLE
Possible bug in ground truth for the "wave" dataset.

### ISSUE THREAD

**Issue by julesberman** [mkirchmeyer/DINo#2]
I was looking at the code which generates the ground truth for the "wave" dataset. As I understand you are using the package [py-pde](https://github.com/zwicker-group/py-pde/tree/master) to solve the 2D wave equation.

On [line 116](https://github.com/mkirchmeyer/DINo/blob/main/data_pdes.py#L116C1-L116C68) in data_pdes.py you define the grid for the solver as 

```
self.grid = UnitGrid([self.size, self.size], periodic=True)
```

where `self.size` is passed in from utils.py and is set to the value [64](https://github.com/mkirchmeyer/DINo/blob/main/utils.py#L35)

I assume the intent here is to define a 2D grid on the domain [-1,1]^2 with 64x64 grid points as described in your paper on page 18 in the appendix.

But, as I understand it, the `UnitGrid` function from py-pde will define a grid on [0,N] with unit length separating each grid point. See documentation [here](https://py-pde.readthedocs.io/en/latest/packages/pde.grids.cartesian.html#pde.grids.cartesian.UnitGrid). If this is the case your code will solve the wave equation on the domain [0,64]^2 with 64x64 grid points, which is different from what is reported in the paper.

This small code snippet should illustrate the point:
```
from pde import UnitGrid
size = 64
grid = UnitGrid([size, size], periodic=True)
print(grid.axes_bounds)
```
which should print:
```
((0.0, 64.0), (0.0, 64.0))
```

Please let me know if I am mistaken. Happy to discuss more.

**Comment by yuan-yin** [comment]
Thank you, Jules, for your interest in our paper! We appreciate your feedback. Indeed there is a glitch in the correspondence between the code and the dataset description, so to reproduce the results, please use the code in this repository. Given the spatial discretization scheme, the trajectories should be the same if we change the domain to $[-1,1]^2$ and the parameter `speed` to  ~c=64=2x32~ $c=2/32$ (edited after the discussion below), as the cell size has changed. We will make an effort to update the appendix accordingly.

Thanks once again for bringing this to our attention.

**Comment by julesberman** [comment]
The wave speed should decrease no?

In my brief experiments a wave speed of c=1/16 up to T=40 on [-1,1] produces the same data as the `data_pdes.py` file produces on the current settings in the code base (where we have u_tt=c^2∇u).

I choose T=40 because in `data_pdes.py` we have:
```
self.eqs.solve(state, t_range=self.t_horizon * self.n_seq_per_traj, ...
```
where
```
"n_seq_per_traj": 8, 
"t_horizon": 5
```
as defined [here](https://github.com/mkirchmeyer/DINo/blob/main/utils.py#L41C27-L41C64)

The following code snippet should produce an identical solution field to `data_pdes.py` for the same `init_cond` variable:
```
grid = CartesianGrid([[-1, 1]] * 2, 64, periodic=True)
speed = 1/16
param = {"speed": speed, 'bc': 'periodic'}
eqs = WavePDE(**param)
u = ScalarField(grid, init_cond)
state = eqs.get_initial_condition(u)
storage = MemoryStorage()
dt_eval = 0.25
t_range = 40.0
eqs.solve(state, t_range=t_range,
                dt=1e-3, tracker=storage.tracker(dt_eval))
u = np.stack(storage.data, axis=1)
```

Sorry to bother you about this, I just want to make sure I understand the all the parameters on the physical equation being solved here.

**Comment by yuan-yin** [comment]
Yeah, you are right; it is actually $c=\frac{2}{32}$. Sorry for any confusion. (I should not respond at midnight next time😵‍💫). I will incorporate this into the code. Thanks again!

**Comment by julesberman** [comment]
Great, thanks so much!
